// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.microsoft.multiclouddb.perf;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Renders a self-contained HTML perf report (inline CSS + inline SVG charts, no JS,
 * no external assets) — the Java replacement for {@code generate-report-html.sh}.
 * Opens in any browser; print to PDF via the browser dialog.
 */
final class HtmlReport {

    private HtmlReport() {
    }

    static Path write(List<StatRow> stats, List<EnvRow> env, ReportMeta meta, Path outDir) {
        List<String> providers = Reports.providerOrder(stats);
        StringBuilder b = new StringBuilder();
        b.append("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">\n");
        b.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        b.append("<title>Perf Report — ").append(Reports.esc(meta.title())).append("</title>\n");
        b.append(css());
        b.append("</head><body>\n");
        b.append("<h1>Performance Report</h1>\n");
        b.append("<div class=\"meta\"><b>").append(Reports.esc(meta.title()))
                .append("</b> &middot; generated ").append(Reports.esc(meta.generatedUtc()))
                .append(" &middot; source <code>").append(Reports.esc(meta.sourceLabel())).append("</code></div>\n");
        b.append("<div class=\"warn\">Live cloud accounts. Latency &amp; cost depend on region, ")
                .append("provisioned capacity, client-host location, and time-of-day tenant load. Repeated ")
                .append("runs of a scenario are <b>pooled</b> (percentiles recomputed over the combined ")
                .append("sample); the <code>Runs</code> column shows how many runs contributed.</div>\n");

        preface(b, stats);

        b.append("<h2>1. Environment</h2>\n");
        envTable(b, env, providers);

        b.append("<h2>2. At a glance (charts)</h2>\n");
        b.append("<p class=\"muted\">One panel per scenario. Bars are grouped by operation; ")
                .append("each colored bar is a provider. Read across a row to compare providers on ")
                .append("the same operation.</p>\n");
        charts(b, stats, providers);

        b.append("<h2>3. Cross-provider comparison</h2>\n");
        b.append("<h3>p99 latency &mdash; lower is better (winner highlighted)</h3>\n");
        cmpTable(b, stats, providers, true, "ms", StatRow::p99, false);
        b.append("<h3>Throughput &mdash; higher is better</h3>\n");
        cmpTable(b, stats, providers, false, "", StatRow::throughputOpsSec, false);
        b.append("<h3>Cost (mean, provider units) &mdash; lower is better</h3>\n");
        b.append("<p class=\"muted\">Units differ by provider (Cosmos RU, DynamoDB RCU/WCU, Spanner PU-ms). ")
                .append("Compare within an operation; cross-unit ratios are only rough.</p>\n");
        cmpTable(b, stats, providers, true, "", s -> s.costMean() == null ? -1 : s.costMean(), true);

        b.append("<h2>4. Per-provider detail</h2>\n");
        ppTables(b, stats, providers);

        b.append("<h2>5. Thread-scaling &amp; migration parity</h2>\n");
        parityAndScaling(b, stats, providers, meta.baseline());

        b.append("<footer>Generated by <code>PerfMain</code> (pure Java, no external deps). ")
                .append("Save as PDF via your browser's Print dialog.</footer>\n");
        b.append("</body></html>\n");

        Path dest = outDir.resolve(MarkdownReport.sanitize(meta.title()) + "-REPORT.html");
        try {
            Files.createDirectories(outDir);
            Files.writeString(dest, b.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("Failed writing HTML report", e);
        }
        return dest;
    }

    @FunctionalInterface
    interface MetricFn {
        double apply(StatRow s);
    }

    private static void envTable(StringBuilder b, List<EnvRow> env, List<String> providers) {
        b.append("<table><thead><tr><th>Provider</th><th>Region</th><th>Provisioned capacity</th>")
                .append("<th>Client host</th><th>JDK</th><th>SDK version</th></tr></thead><tbody>\n");
        Map<String, EnvRow> byP = new LinkedHashMap<>();
        for (EnvRow e : env) {
            byP.put(e.provider(), e);
        }
        for (String p : providers) {
            EnvRow e = byP.get(p);
            if (e == null) {
                continue;
            }
            b.append("<tr><td>").append(Reports.esc(p)).append("</td><td>").append(Reports.esc(e.region()))
                    .append("</td><td>").append(Reports.esc(e.provisionedCapacity()))
                    .append("</td><td>").append(Reports.esc(e.hostLabel()))
                    .append("</td><td>").append(Reports.esc(e.jdk()))
                    .append("</td><td>").append(Reports.esc(e.sdkVersion())).append("</td></tr>\n");
        }
        b.append("</tbody></table>\n");
    }

    private static String color(String provider) {
        return switch (provider) {
            case "cosmos" -> "#0078D4";
            case "dynamo" -> "#FF9900";
            case "spanner" -> "#34A853";
            default -> "#6a737d";
        };
    }

    /** Renders one chart panel per scenario (p99, throughput, and — when present — cost),
     *  with operation-only bar labels so a reader isn't parsing "op / scenario / threads". */
    private static void charts(StringBuilder b, List<StatRow> stats, List<String> providers) {
        java.util.LinkedHashSet<String> scenarios = new java.util.LinkedHashSet<>();
        for (StatRow s : stats) {
            scenarios.add(s.scenario());
        }
        for (String sc : scenarios) {
            List<StatRow> sub = new java.util.ArrayList<>();
            java.util.Set<Integer> threadSet = new java.util.HashSet<>();
            boolean hasCost = false;
            for (StatRow s : stats) {
                if (s.scenario().equals(sc)) {
                    sub.add(s);
                    threadSet.add(s.threads());
                    if (s.costMean() != null && s.costMean() > 0) {
                        hasCost = true;
                    }
                }
            }
            boolean showThreads = threadSet.size() > 1;
            b.append("<h3>Scenario ").append(Reports.esc(sc)).append(" &mdash; ")
                    .append(Reports.esc(scenarioDesc(sc))).append("</h3>\n");
            b.append(svgChart(sub, providers, "p99 latency", true, "ms", StatRow::p99, showThreads));
            b.append(svgChart(sub, providers, "Throughput", false, "ops/s",
                    StatRow::throughputOpsSec, showThreads));
            if (hasCost) {
                b.append(svgChart(sub, providers, "Cost (mean request charge)", true,
                        "units", s -> s.costMean() == null ? -1 : s.costMean(), showThreads));
            }
        }
    }

    private static String svgChart(List<StatRow> stats, List<String> providers,
                                   String title, boolean lowerBetter, String unit, MetricFn metric,
                                   boolean showThreads) {
        Map<String, Map<String, Double>> groups = new LinkedHashMap<>();
        Map<String, StatRow> anyRow = new LinkedHashMap<>();
        double gmax = 0;
        for (StatRow s : stats) {
            double v = metric.apply(s);
            if (v < 0) {
                continue;
            }
            String label = showThreads ? s.operation() + " @" + s.threads() + "t" : s.operation();
            groups.computeIfAbsent(label, k -> new LinkedHashMap<>()).put(s.provider(), v);
            anyRow.putIfAbsent(label, s);
            if (v > gmax) {
                gmax = v;
            }
        }
        if (groups.isEmpty()) {
            return "<p class=\"muted\">No data for " + Reports.esc(title) + ".</p>\n";
        }
        if (gmax <= 0) {
            gmax = 1;
        }
        int barH = 18, gap = 5, groupPad = 18, leftPad = 130, chartW = 560, topPad = 64;
        int totalH = topPad;
        for (Map<String, Double> g : groups.values()) {
            int cp = 0;
            for (String p : providers) {
                if (g.containsKey(p)) {
                    cp++;
                }
            }
            totalH += cp * (barH + gap) + groupPad;
        }
        int w = leftPad + chartW + 120;
        StringBuilder b = new StringBuilder();
        b.append(String.format(Locale.ROOT,
                "<svg class=\"chart\" width=\"%d\" height=\"%d\" viewBox=\"0 0 %d %d\" xmlns=\"http://www.w3.org/2000/svg\">\n",
                w, totalH, w, totalH));
        b.append("<text x=\"8\" y=\"22\" class=\"ct\">").append(Reports.esc(title)).append("</text>\n");
        b.append("<text x=\"8\" y=\"40\" class=\"cs\">").append(Reports.esc(unit)).append(" &#183; ")
                .append(lowerBetter ? "lower" : "higher").append(" is better</text>\n");
        int cx = 8;
        for (String p : providers) {
            b.append(String.format(Locale.ROOT,
                    "<rect x=\"%d\" y=\"48\" width=\"11\" height=\"11\" fill=\"%s\" rx=\"2\"/>\n", cx, color(p)));
            b.append(String.format(Locale.ROOT, "<text x=\"%d\" y=\"58\" class=\"cl\">%s</text>\n",
                    cx + 15, Reports.esc(p)));
            cx += 90;
        }
        int y = topPad;
        for (Map.Entry<String, Map<String, Double>> e : groups.entrySet()) {
            b.append(String.format(Locale.ROOT, "<text x=\"8\" y=\"%d\" class=\"cg\">%s</text>\n",
                    y + 12, Reports.esc(e.getKey())));
            for (String p : providers) {
                Double v = e.getValue().get(p);
                if (v == null) {
                    continue;
                }
                double bw = (v / gmax) * chartW;
                if (bw < 2 && v > 0) {
                    bw = 2;
                }
                b.append(String.format(Locale.ROOT,
                        "<rect x=\"%d\" y=\"%d\" width=\"%.1f\" height=\"%d\" fill=\"%s\" rx=\"2\"/>\n",
                        leftPad, y, bw, barH, color(p)));
                b.append(String.format(Locale.ROOT, "<text x=\"%.1f\" y=\"%d\" class=\"cv\">%s: %s %s</text>\n",
                        leftPad + bw + 6, y + 12, Reports.esc(p), Reports.num(v), Reports.esc(unit)));
                y += barH + gap;
            }
            y += groupPad;
        }
        b.append("</svg>\n");
        return b.toString();
    }

    private static void cmpTable(StringBuilder b, List<StatRow> stats, List<String> providers,
                                 boolean lowerBetter, String unit, MetricFn metric, boolean byScenarioOnly) {
        b.append("<table><thead><tr><th>Operation</th><th>Scenario</th><th>Threads</th>");
        for (String p : providers) {
            b.append("<th>").append(Reports.esc(p)).append("</th>");
        }
        b.append("<th>Best</th></tr></thead><tbody>\n");

        Map<String, Map<String, Double>> groups = new LinkedHashMap<>();
        Map<String, StatRow> anyRow = new LinkedHashMap<>();
        for (StatRow s : stats) {
            double v = metric.apply(s);
            String key = byScenarioOnly ? s.operation() + "\u0001" + s.scenario()
                    : s.operation() + "\u0001" + s.scenario() + "\u0001" + s.threads();
            if (v >= 0) {
                groups.computeIfAbsent(key, k -> new LinkedHashMap<>()).put(s.provider(), v);
            }
            anyRow.putIfAbsent(key, s);
        }
        for (Map.Entry<String, StatRow> entry : anyRow.entrySet()) {
            StatRow r = entry.getValue();
            Map<String, Double> vals = groups.getOrDefault(entry.getKey(), Map.of());
            String best = null;
            double bestVal = 0;
            for (Map.Entry<String, Double> e : vals.entrySet()) {
                double v = e.getValue();
                if (lowerBetter && v <= 0) {
                    continue;
                }
                if (best == null || (lowerBetter ? v < bestVal : v > bestVal)) {
                    best = e.getKey();
                    bestVal = v;
                }
            }
            b.append("<tr><td>").append(Reports.esc(r.operation())).append("</td><td>")
                    .append(Reports.esc(r.scenario())).append("</td><td>")
                    .append(byScenarioOnly ? "&mdash;" : String.valueOf(r.threads())).append("</td>");
            for (String p : providers) {
                Double v = vals.get(p);
                if (v == null) {
                    b.append("<td class=\"muted\">&mdash;</td>");
                } else if (p.equals(best)) {
                    b.append("<td class=\"win\">").append(Reports.num(v)).append(' ').append(Reports.esc(unit)).append("</td>");
                } else {
                    double ratio = bestVal > 0 ? (lowerBetter ? v / bestVal : bestVal / v) : 0;
                    b.append("<td>").append(Reports.num(v)).append(' ').append(Reports.esc(unit))
                            .append(" <span class=\"rel\">(").append(String.format(Locale.ROOT, "%.2f", ratio))
                            .append("&#215;)</span></td>");
                }
            }
            b.append("<td class=\"bestp\">").append(best == null ? "&mdash;" : Reports.esc(best)).append("</td></tr>\n");
        }
        b.append("</tbody></table>\n");
    }

    private static void ppTables(StringBuilder b, List<StatRow> stats, List<String> providers) {
        for (String p : providers) {
            boolean any = stats.stream().anyMatch(s -> s.provider().equals(p));
            if (!any) {
                continue;
            }
            b.append("<h3>").append(Reports.esc(p)).append("</h3>\n");
            b.append("<table><thead><tr><th>Op</th><th>Measures</th><th>Scn</th><th>Thr</th><th>Doc B</th><th>Page</th>")
                    .append("<th>Runs</th><th>Count</th><th>p50 ms</th><th>p90 ms</th><th>p99 ms</th>")
                    .append("<th>max ms</th><th>ops/s</th><th>cost</th><th>err</th></tr></thead><tbody>\n");
            for (StatRow s : stats) {
                if (!s.provider().equals(p)) {
                    continue;
                }
                b.append("<tr><td>").append(Reports.esc(s.operation())).append("</td><td>")
                        .append(Reports.esc(Reports.opMeasures(s.operation()))).append("</td><td>")
                        .append(Reports.esc(s.scenario())).append("</td><td>").append(s.threads())
                        .append("</td><td>").append(s.docSizeBytes()).append("</td><td>")
                        .append(s.pageSize() == null ? "" : s.pageSize()).append("</td><td>")
                        .append(s.runCount()).append("</td><td>").append(s.count()).append("</td><td>")
                        .append(Reports.num(s.p50())).append("</td><td>").append(Reports.num(s.p90()))
                        .append("</td><td>").append(Reports.num(s.p99())).append("</td><td>")
                        .append(Reports.num(s.max())).append("</td><td>").append(Reports.num(s.throughputOpsSec()))
                        .append("</td><td>").append(Reports.numOrDash(s.costMean())).append("</td><td>")
                        .append(String.format(Locale.ROOT, "%.4f", s.errorRate())).append("</td></tr>\n");
            }
            b.append("</tbody></table>\n");
        }
    }

    private static void preface(StringBuilder b, List<StatRow> stats) {
        java.util.LinkedHashSet<String> scenarios = new java.util.LinkedHashSet<>();
        java.util.LinkedHashSet<String> ops = new java.util.LinkedHashSet<>();
        for (StatRow s : stats) {
            scenarios.add(s.scenario());
            ops.add(s.operation());
        }
        b.append("<h2>What was tested &amp; how to read this</h2>\n");
        b.append("<p>Each <b>operation</b> below was executed many times against a live account through ")
                .append("the portable <code>MulticloudDbClient</code>; every call is timed end-to-end (SDK ")
                .append("translation + network + service, including retries) and its provider-reported cost ")
                .append("captured where available. Operations run inside these <b>scenarios</b>:</p>\n<ul>\n");
        for (String sc : scenarios) {
            b.append("<li><b>").append(Reports.esc(sc)).append("</b> &mdash; ")
                    .append(Reports.esc(scenarioDesc(sc))).append("</li>\n");
        }
        b.append("</ul>\n<p class=\"muted\">Operations exercised this run: ")
                .append(Reports.esc(String.join(", ", ops))).append(".</p>\n");
        b.append("<p><b>Reading the numbers:</b></p>\n<ul>\n")
                .append("<li><b>p50 / p90 / p99 / max ms</b> &mdash; end-to-end latency percentiles; p99 is ")
                .append("the tail 1% of calls. <b>Lower is better.</b></li>\n")
                .append("<li><b>ops/s</b> &mdash; sustained throughput at the stated thread count. ")
                .append("<b>Higher is better.</b></li>\n")
                .append("<li><b>cost</b> &mdash; provider-reported request charge in native units (Cosmos RU, ")
                .append("DynamoDB RCU/WCU, Spanner PU-ms). Compare <i>within</i> an operation only.</li>\n")
                .append("<li><b>Runs / Count</b> &mdash; pooled runs and total sampled calls. <b>err</b> is the ")
                .append("fraction of failed calls (throttling/errors); values &gt; 0 make latency optimistic.</li>\n")
                .append("<li><b>Cross-provider tables</b> highlight the winner per operation; the <b>cost ")
                .append("sub-matrix</b> flags functional-equal operations that cost &ge;10&times; more on one ")
                .append("provider.</li>\n")
                .append("<li><b>Migration parity</b> answers goal 3 &mdash; PASS means a provider keeps up with ")
                .append("the baseline at the <i>same</i> thread count (no need to add threads when migrating); ")
                .append("CHECK means it would need more threads.</li>\n</ul>\n");
    }

    private static String scenarioDesc(String sc) {
        switch (sc) {
            case "S1":
                return "point operations - create / read / update / delete of a single item";
            case "S2":
                return "point operations (secondary variant)";
            case "S3":
                return "query - partition-scoped vs unscoped (single-partition read vs cross-partition scan)";
            case "S4":
                return "query - page-size sweep";
            case "S5":
                return "query - predicate-count sweep";
            case "S6":
                return "concurrency sweep - point operations repeated across thread levels";
            case "S7":
                return "change feed - incremental read of changes (capability-gated)";
            default:
                return "custom scenario";
        }
    }

    private static void parityAndScaling(StringBuilder b, List<StatRow> stats,
                                        List<String> providers, String baseline) {
        b.append("<p class=\"muted\"><strong>Goal 3 &mdash; migrated apps must not need more threads.</strong> ")
                .append("At each matched thread count a target provider must reach &ge; the baseline throughput ")
                .append("and no worse than baseline p99; otherwise it would need extra threads to keep up ")
                .append("(tolerance &plusmn;")
                .append(String.format(Locale.ROOT, "%.0f%%", ThreadAnalysis.TOLERANCE * 100)).append(").</p>\n");

        List<ThreadAnalysis.ParityRow> parity = ThreadAnalysis.parity(stats, providers, baseline);
        if (parity.isEmpty()) {
            b.append("<p class=\"muted\">Need at least two providers (baseline + target) with overlapping ")
                    .append("operations to compute parity.</p>\n");
        } else {
            List<String> targets = new java.util.ArrayList<>();
            for (String pr : providers) {
                if (!pr.equals(baseline)) {
                    targets.add(pr);
                }
            }
            b.append("<h3>Migration parity vs baseline <code>").append(Reports.esc(baseline))
                    .append("</code> (migration source)</h3>\n");
            b.append("<table><thead><tr><th>Op</th><th>Scn</th><th>Thr</th><th>")
                    .append(Reports.esc(baseline)).append(" ops/s</th><th>").append(Reports.esc(baseline))
                    .append(" p99</th>");
            for (String t : targets) {
                b.append("<th>").append(Reports.esc(t)).append(" ops/s (&times;base)</th><th>")
                        .append(Reports.esc(t)).append(" p99 (&times;base)</th>");
            }
            b.append("<th>Verdict</th></tr></thead><tbody>\n");
            for (ThreadAnalysis.ParityRow r : parity) {
                b.append("<tr><td>").append(Reports.esc(r.operation())).append("</td><td>")
                        .append(Reports.esc(r.scenario())).append("</td><td>").append(r.threads())
                        .append("</td><td>").append(Reports.num(r.baseTput())).append("</td><td>")
                        .append(Reports.num(r.baseP99())).append("</td>");
                for (String t : targets) {
                    Double tt = r.targetTput().get(t);
                    Double tp = r.targetP99().get(t);
                    if (tt == null) {
                        b.append("<td>&mdash;</td><td>&mdash;</td>");
                    } else {
                        b.append("<td>").append(Reports.num(tt)).append(" <span class=\"rel\">")
                                .append(ratio(tt, r.baseTput())).append("</span></td><td>")
                                .append(Reports.num(tp)).append(" <span class=\"rel\">")
                                .append(ratio(tp, r.baseP99())).append("</span></td>");
                    }
                }
                b.append("<td class=\"").append(r.pass() ? "pass" : "fail").append("\">")
                        .append(r.pass() ? "&#10003; PASS" : "&#9888; CHECK").append("</td></tr>\n");
            }
            b.append("</tbody></table>\n");
        }

        List<ThreadAnalysis.ScalingRow> scaling = ThreadAnalysis.scaling(stats, providers);
        if (!ThreadAnalysis.multiThread(stats) || scaling.isEmpty()) {
            b.append("<p class=\"muted\">Single thread level in this run &mdash; re-run with a sweep ")
                    .append("(e.g. <code>--threads 1,8,32</code>) to see throughput scale with concurrency.</p>\n");
            return;
        }
        List<Integer> levels = ThreadAnalysis.threadLevels(stats);
        b.append("<h3>Thread-scaling (throughput ops/s by thread count)</h3>\n");
        b.append("<table><thead><tr><th>Provider</th><th>Op</th><th>Scn</th>");
        for (Integer t : levels) {
            b.append("<th>").append(t).append("t</th>");
        }
        b.append("<th>Peak</th><th>Scale</th></tr></thead><tbody>\n");
        for (ThreadAnalysis.ScalingRow r : scaling) {
            b.append("<tr><td>").append(Reports.esc(r.provider())).append("</td><td>")
                    .append(Reports.esc(r.operation())).append("</td><td>")
                    .append(Reports.esc(r.scenario())).append("</td>");
            for (Integer t : levels) {
                Double v = r.tputByThreads().get(t);
                b.append("<td>").append(v == null ? "&mdash;" : Reports.num(v)).append("</td>");
            }
            b.append("<td>").append(r.peakThreads()).append("t</td><td>")
                    .append(String.format(Locale.ROOT, "%.1f&times;", r.scalingFactor())).append("</td></tr>\n");
        }
        b.append("</tbody></table>\n");
        b.append("<p class=\"muted\">Scale = peak throughput &divide; throughput at the lowest thread count. ")
                .append("Near 1.0&times; means the workload is already saturated (more threads will not help).</p>\n");
    }

    private static String ratio(double target, double base) {
        if (base <= 0) {
            return "&mdash;";
        }
        return String.format(Locale.ROOT, "%.2f&times;", target / base);
    }

    private static String css() {
        return "<style>\n"
                + ":root{--fg:#1b1f23;--mut:#6a737d;--line:#e1e4e8;--win:#e6f4ea;--winb:#137333}\n"
                + "*{box-sizing:border-box}\n"
                + "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;"
                + "color:var(--fg);max-width:1000px;margin:24px auto;padding:0 18px;line-height:1.45}\n"
                + "h1{font-size:24px;margin:0 0 4px} h2{font-size:19px;border-bottom:2px solid var(--line);padding-bottom:6px;margin-top:34px}\n"
                + "h3{font-size:15px;margin:18px 0 6px;color:#24292e}\n"
                + ".meta{color:var(--mut);font-size:13px;margin-bottom:8px}\n"
                + ".warn{background:#fff8c5;border:1px solid #eedc82;border-radius:6px;padding:8px 12px;font-size:13px;margin:12px 0}\n"
                + "table{border-collapse:collapse;width:100%;font-size:13px;margin:8px 0 4px}\n"
                + "th,td{border:1px solid var(--line);padding:5px 8px;text-align:left}\n"
                + "th{background:#f6f8fa;font-weight:600} tr:nth-child(even) td{background:#fbfcfd}\n"
                + "td.win{background:var(--win);font-weight:700;color:var(--winb)}\n"
                + "td.pass{background:var(--win);font-weight:700;color:var(--winb)} td.fail{background:#fff0f0;font-weight:700;color:#b3261e}\n"
                + "td.bestp{font-weight:700;text-transform:capitalize} .rel{color:var(--mut);font-size:11px}\n"
                + ".muted{color:var(--mut)} .chart{max-width:100%;height:auto;margin:6px 0 18px;border:1px solid var(--line);border-radius:6px;background:#fff}\n"
                + ".ct{font-size:15px;font-weight:700;fill:#1b1f23} .cs{font-size:11px;fill:#6a737d}\n"
                + ".cg{font-size:12px;font-weight:600;fill:#24292e} .cv{font-size:11px;fill:#24292e} .cl{font-size:12px;fill:#24292e}\n"
                + "footer{margin-top:32px;color:var(--mut);font-size:12px;border-top:1px solid var(--line);padding-top:10px}\n"
                + "</style>\n";
    }
}
